os: linux
dist: xenial
services:
- docker
language: python
python:
- '3.9'
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
branches:
  only:
  - master
  - "/^[0-9]*\\.[0-9]*\\.[0-9]*$/"
jobs:
  fast_finish: true
  include:
  - stage: unit tests
    install:
    - make requirements_test
    script:
    - make test
  - stage: tag version
    if: branch = master AND type != pull_request AND tag IS NOT present
    script:
    - bash .ci/tag_version.sh
    env:
      secure: FVguRdfZcMWN5SQy7/sK/QAXFsErlIfNsU4E0bsKhUBvbLdL2TTZfkudRWx9tYldfZRqnBWgc11+1QN3Hzl813Lutf+IoUQG1HrLcF9xS46qqyz8jOOAfrj7ZS+rx7p8m9QzpLqRW30uzdHKKBGeTxODvM3/mjjDny6DCS6U/1yyUT7juTsc2FImjIP88IKfIx84i8ZIQ6K2Fsb2JYOzxH+dsPxrxvAy6CtAIAkaHFIUuEeVbpbPgdIZBhsaMwuQzFJnsjclm15yiokwAitrOEJ+s/gzyvy0iXUs1rz/G9jaWy/6mjy/gcSKYUOzk7kze+gAlrTEyhzWkkOk8z5K8CV0YKIZLaBZKUUjKi57dosMR/ALSMV3+4n/yD2OcKypQcHIJRiMgt62bW/Zmw0fQhhOCojTxvksvKaG4EJdnZ+F7YOU+2/e1Vc8uYa3JZl5473s03pE9celr6wLEUgrAXD4APRIyoH/8olcJIdZAUQ6sFiQa9okSgB9rSniz3Rc/S+bYThiL5/zZstJXjdS1+YJk9iDfB3JqidMK7IXZvTj8H9ywGeIsifM/Heo73Wqba7QjtMWWuI0yV2B2ugE3dQuyOBqh5XYQuhUIrGFrRA2SjEw5RUtVzjkX6Oov884ip5azcjqY9jAzHD/8th3ZZv6ju+5b/9E4NvrJX1WJ20=
  - stage: deploy arm
    arch: arm64
    install: skip
    script: skip
    if: type != pull_request
    deploy:
    - provider: script
      script: bash .ci/deploy.sh
      on:
        all_branches: true
    env:
    - PATH=~/.ruby/bin:$PATH
    - GEM_HOME=~/.ruby

  - stage: deploy amd64 and manifest
    install: skip
    script: skip
    if: type != pull_request
    deploy:
    - provider: script
      script: bash .ci/deploy.sh
      on:
        all_branches: true
